// Copyright (c) Microsoft Corporation. All rights reserved. See License.txt in the project root for license information.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Microsoft.Practices.EnterpriseLibrary.Validation.Integration.AspNet.PropertyProxyValidator.#Microsoft.Practices.EnterpriseLibrary.Validation.Integration.IValidationIntegrationProxy.GetMemberValueAccessBuilder()", Justification = "By original design. Low risk.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Microsoft.Practices.EnterpriseLibrary.Validation.Integration.AspNet.PropertyProxyValidator.#Microsoft.Practices.EnterpriseLibrary.Validation.Integration.IValidationIntegrationProxy.GetRawValue()", Justification = "By original design. Low risk.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Microsoft.Practices.EnterpriseLibrary.Validation.Integration.AspNet.PropertyProxyValidator.#Microsoft.Practices.EnterpriseLibrary.Validation.Integration.IValidationIntegrationProxy.PerformCustomValueConversion(Microsoft.Practices.EnterpriseLibrary.Validation.Integration.ValueConvertEventArgs)", Justification = "By original design. Low risk.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Microsoft.Practices.EnterpriseLibrary.Validation.Integration.AspNet.PropertyProxyValidator.#Microsoft.Practices.EnterpriseLibrary.Validation.Integration.IValidationIntegrationProxy.ProvidesCustomValueConversion", Justification = "By original design. Low risk.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Microsoft.Practices.EnterpriseLibrary.Validation.Integration.AspNet.PropertyProxyValidator.#Microsoft.Practices.EnterpriseLibrary.Validation.Integration.IValidationIntegrationProxy.Ruleset", Justification = "By original design. Low risk.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Microsoft.Practices.EnterpriseLibrary.Validation.Integration.AspNet.PropertyProxyValidator.#Microsoft.Practices.EnterpriseLibrary.Validation.Integration.IValidationIntegrationProxy.ValidatedPropertyName", Justification = "By original design. Low risk.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Microsoft.Practices.EnterpriseLibrary.Validation.Integration.AspNet.PropertyProxyValidator.#Microsoft.Practices.EnterpriseLibrary.Validation.Integration.IValidationIntegrationProxy.ValidatedType", Justification = "By original design. Low risk.")]
